name        : glproto
version     : 1.4.17
release     : 5
source      :
    - http://xorg.freedesktop.org/releases/individual/proto/glproto-1.4.17.tar.gz : 9d8130fec2b98bd032db7730fa092dd9dec39f3de34f4bb03ceb43b9903dbc96
license     :
    - MIT
summary     : OpenGL Extension to the X Window System
component   : xorg.proto
patterns    : /
description : |
    This extension defines a protocol for the client to send 3D rendering commands to the X server
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
